name: Check_Metrix
on: [push, workflow_dispatch]
jobs:
    building:
        runs-on: windows-latest
        steps:
            - name : check repository
              uses: actions/checkout@v4
            - name: npm install
              uses: actions/setup-node@v3
              with:
                 node-version: 14
            - name: npm install
              run: npm ci 
                    
            - name: build code
              run: npm run build

            

    
   
