name: Deployment_git_cache
on:
    push:
        branches:
          - master
    workflow_dispatch:
jobs:
   Testing:
     runs-on: ubuntu-latest
     steps:
      - name: "invokeing repo"
        uses: actions/checkout@v4
      - name: check cache
        id: cache-setup
        uses: actions/cache@v4
        with:
            path: node_modules
            key: Cache-setup-${{hashFiles('**/package-lock.json')}}
            restore-keys:
                Cache-setup-
      -  name: install NPM1
         run: npm install      
      
      -  name: Upload repository1
         uses: actions/upload-artifact@v4
         with:
            name: test_folder
            path:  ${{github.workspace}}

        
   Deployment:
     needs: Testing
     runs-on: ubuntu-latest
     steps:
      - name: "invokeing repo"
        uses: actions/checkout@v4
      - name: check cache
        id: cache-setup
        uses: actions/cache@v4
        with:
            path: node_modules
            key: Cache-setup-${{hashFiles('**/package-lock.json')}}
            restore-keys:
                Cache-setup-
      -  name: Download Artifacts
         uses: actions/download-artifact@v4
         with:
            name: test_folder
            





    