name: Website Deployment1
on:
  push:
    branches:
      - main   
      - master   
jobs:
  lint:
    runs-on: windows-latest
    outputs:
        script_file: ${{steps.nam_list.outputs.script_file}}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name : what is my name 
        id: nam_list
        run: |
         $a= "file testing"
         echo  "script_file=$a" >> $env:GITHUB_OUTPUT
      - name: npm install
        run: npm install
      - name : npm test
        id: npm_test_status
        run: npm test
      - name: Upload artifacts
        uses: action/upload-artifacts@v4
        with:
          name: Upload 
          path: test

  deploy:
       needs: lint
       runs-on: windows-latest
       steps:
        - name: Get code1
          uses: actions/checkout@v3
        - name : what is my name 
          id: nam_list
          run: |
            write-host ${{ needs.lint.outputs.script_file }}

    
       