name: Deployment_git_cache
on:
    push:
        branches:
          - master
    workflow_dispatch:
jobs:
   Testing:
     runs-on: ubuntu-latest
     steps:
      - name: "invokeing repo"
        uses: actions/checkout@v4
      - name: check cache
        id: cache-setup1
        uses: actions/cache@v4
        with:
            path: node_modules
            key: Cache-setup-${{hashFiles('**/package-lock.json')}}
            restore-keys:
                Cache-setup-
      - name: install NPM1
        if: failure() && steps.cache-setup1.outputs != 'false'
        run: npm install 
      -  name: Npm testing command
         continue-on-error: true
         run: npm test     
      -  name: Upload repository1
         id: Upload-arti
         uses: actions/upload-artifact@v4
         with:
            name: test_folder
            path:  ${{github.workspace}}

      -  name: check Upload artifacts1
         if: steps.Upload-arti.outcome == 'success'
         run: echo "all successfully uploaded"


        
   Deployment:
     needs: Testing
     runs-on: ubuntu-latest
     steps:
      - name: "invokeing repo1"
        uses: actions/checkout@v4
      - name: check cache
        id: cache-setup
        uses: actions/cache@v4
        with:
            path: node_modules
            key: Cache-setup-${{hashFiles('**/package-lock.json')}}
            restore-keys:
                Cache-setup-
      -  name: Download Artifacts
         uses: actions/download-artifact@v4
         with:
            name: test_folder
            





    